# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interests', '0003_auto_20170406_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
