# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0004_interest_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interests.Interest')),
            ],
        ),
    ]
