# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0005_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
