# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0006_interest_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
