# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interests', '0009_remove_userprofile_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fb_accaount',
            new_name='fb_account',
        ),
    ]
